/**
 * Orders Routes with Smart Task Generation
 */
const express = require('express');
const router = express.Router();
const { Op } = require('sequelize');
const { Order, OrderItem, Customer, Product, PriceTier, ProductPrice, Crop, MushroomSpecies, Task } = require('../models');
const { auth } = require('../middleware/auth');

// Helper: Add days to date
const addDays = (date, days) => {
  const result = new Date(date);
  result.setDate(result.getDate() + days);
  return result.toISOString().split('T')[0];
};

// Helper: Subtract days from date
const subtractDays = (date, days) => {
  const result = new Date(date);
  result.setDate(result.getDate() - days);
  return result.toISOString().split('T')[0];
};

// Helper: Calculate tray requirements
const calculateTrayRequirements = (product, quantity, crop) => {
  // Assume standard 10x20 tray yields based on crop
  const yieldPerTray = crop.expectedYieldGrams || 200; // grams per tray
  const unitSizeGrams = (product.unitSize || 2) * 28.35; // Convert oz to grams
  const totalGramsNeeded = quantity * unitSizeGrams;
  
  const traysNeeded = Math.ceil(totalGramsNeeded / yieldPerTray);
  const sowRateG = crop.defaultSowGrams || 30;
  const sowRateOz = sowRateG / 28.35;
  
  return {
    trayCount: traysNeeded,
    sowRateGPerTray: sowRateG,
    sowRateOzPerTray: Math.round(sowRateOz * 100) / 100,
    totalSeedWeightG: sowRateG * traysNeeded,
    totalSeedWeightOz: Math.round((sowRateG * traysNeeded / 28.35) * 100) / 100,
    soakTimeHours: crop.soakHours || 0
  };
};

// Helper: Calculate block requirements for mushrooms
const calculateBlockRequirements = (product, quantity, species) => {
  const unitSizeLbs = (product.unitSize || 8) / 16; // Convert oz to lbs
  const totalLbsNeeded = quantity * unitSizeLbs;
  const avgYieldPerBlock = ((species.yieldPerBlockLbsMin || 2) + (species.yieldPerBlockLbsMax || 3)) / 2;
  const blocksNeeded = Math.ceil(totalLbsNeeded / avgYieldPerBlock);
  
  return {
    blockCount: blocksNeeded,
    expectedYieldLbs: blocksNeeded * avgYieldPerBlock
  };
};

// Helper: Generate tasks for a microgreen order item
const generateMicrogreenTasks = async (order, orderItem, product, crop, farmId) => {
  const tasks = [];
  const harvestDate = order.harvestDate || order.deliveryDate;
  const reqs = calculateTrayRequirements(product, orderItem.quantity, crop);
  
  // Calculate dates working backwards from harvest
  const daysToHarvest = crop.daysToHarvest || 7;
  const blackoutDays = crop.blackoutDays || 3;
  const soakHours = crop.soakHours || 0;
  
  const sowDate = subtractDays(harvestDate, daysToHarvest);
  const soakDate = soakHours > 0 ? subtractDays(sowDate, 1) : null;
  const uncoverDate = addDays(sowDate, blackoutDays);
  
  const baseTaskData = {
    farmId,
    category: 'microgreens',
    priority: 'high',
    autoGenerated: true,
    sourceType: 'order',
    sourceId: order.id,
    cropId: crop.id,
    cropName: `${crop.name}${crop.variety ? ' - ' + crop.variety : ''}`,
    seedType: crop.variety || crop.name,
    trayCount: reqs.trayCount,
    sowRateOzPerTray: reqs.sowRateOzPerTray,
    sowRateGPerTray: reqs.sowRateGPerTray,
    soakTimeHours: reqs.soakTimeHours,
    totalSeedWeightOz: reqs.totalSeedWeightOz,
    totalSeedWeightG: reqs.totalSeedWeightG,
    harvestDate
  };
  
  // Soak task (if needed)
  if (soakHours > 0) {
    tasks.push({
      ...baseTaskData,
      title: `Soak ${crop.name}`,
      taskType: 'soak',
      dueDate: soakDate,
      description: `Soak ${reqs.totalSeedWeightG.toFixed(0)}g (${reqs.totalSeedWeightOz.toFixed(2)}oz) for ${soakHours}h. For ${reqs.trayCount} tray(s).`
    });
  }
  
  // Sow task
  tasks.push({
    ...baseTaskData,
    title: `Sow ${crop.name}`,
    taskType: 'sow',
    dueDate: sowDate,
    description: `Sow ${reqs.trayCount} tray(s) at ${reqs.sowRateGPerTray}g/tray. Cover for blackout.`
  });
  
  // Uncover task (move to light)
  tasks.push({
    ...baseTaskData,
    title: `Uncover ${crop.name}`,
    taskType: 'uncover',
    dueDate: uncoverDate,
    description: `Move ${reqs.trayCount} tray(s) from blackout to grow lights.`
  });
  
  // Harvest task
  tasks.push({
    ...baseTaskData,
    title: `Harvest ${crop.name}`,
    taskType: 'harvest',
    dueDate: harvestDate,
    description: `Harvest ${reqs.trayCount} tray(s) for order ${order.orderNumber}.`
  });
  
  return tasks;
};

// Helper: Generate tasks for a mushroom order item
const generateMushroomTasks = async (order, orderItem, product, species, farmId) => {
  const tasks = [];
  const harvestDate = order.harvestDate || order.deliveryDate;
  const reqs = calculateBlockRequirements(product, orderItem.quantity, species);
  
  // Calculate dates working backwards from harvest
  const daysToHarvest = species.daysToFirstHarvest || 7;
  const fruitingStartDate = subtractDays(harvestDate, daysToHarvest);
  
  const baseTaskData = {
    farmId,
    category: 'mushrooms',
    priority: 'high',
    autoGenerated: true,
    sourceType: 'order',
    sourceId: order.id,
    speciesId: species.id,
    speciesName: `${species.name} (${species.strainCode})`,
    blockCount: reqs.blockCount,
    expectedYieldLbs: reqs.expectedYieldLbs,
    harvestDate
  };
  
  // Move to fruiting task
  tasks.push({
    ...baseTaskData,
    title: `Move ${species.name} to fruiting`,
    taskType: 'move_to_fruiting',
    dueDate: fruitingStartDate,
    description: `Move ${reqs.blockCount} block(s) to fruiting room. ${species.initiationMethod || ''}`
  });
  
  // Harvest task
  tasks.push({
    ...baseTaskData,
    title: `Harvest ${species.name}`,
    taskType: 'harvest',
    dueDate: harvestDate,
    description: `Harvest ~${reqs.expectedYieldLbs.toFixed(1)} lbs from ${reqs.blockCount} block(s) for order ${order.orderNumber}.`
  });
  
  return tasks;
};

// Generate all tasks for an order
const generateOrderTasks = async (order, farmId) => {
  // Delete existing auto-generated tasks for this order
  await Task.destroy({
    where: { sourceType: 'order', sourceId: order.id, autoGenerated: true }
  });
  
  // Get order items with product info
  const orderItems = await OrderItem.findAll({
    where: { orderId: order.id },
    include: [{ model: Product }]
  });
  
  const allTasks = [];
  
  for (const item of orderItems) {
    const product = item.Product;
    if (!product) continue;
    
    if (product.category === 'microgreens' && product.cropId) {
      const crop = await Crop.findByPk(product.cropId);
      if (crop) {
        const tasks = await generateMicrogreenTasks(order, item, product, crop, farmId);
        allTasks.push(...tasks);
      }
    } else if (product.category === 'mushrooms' && product.speciesId) {
      const species = await MushroomSpecies.findByPk(product.speciesId);
      if (species) {
        const tasks = await generateMushroomTasks(order, item, product, species, farmId);
        allTasks.push(...tasks);
      }
    }
  }
  
  // Bulk create tasks
  if (allTasks.length > 0) {
    await Task.bulkCreate(allTasks);
  }
  
  return allTasks.length;
};

// Get all orders
router.get('/', auth, async (req, res) => {
  try {
    const orders = await Order.findAll({
      include: [
        { model: Customer, attributes: ['id', 'name', 'type'] },
        { model: OrderItem, include: [{ model: Product }] }
      ],
      order: [['deliveryDate', 'DESC']]
    });
    res.json(orders);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Get today's orders
router.get('/today', auth, async (req, res) => {
  try {
    const today = new Date().toISOString().split('T')[0];
    const orders = await Order.findAll({
      where: { deliveryDate: today },
      include: [{ model: Customer, attributes: ['id', 'name'] }]
    });
    res.json(orders);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Get single order
router.get('/:id', auth, async (req, res) => {
  try {
    const order = await Order.findByPk(req.params.id, {
      include: [
        { model: Customer },
        { model: OrderItem, include: [{ model: Product }] }
      ]
    });
    if (!order) return res.status(404).json({ error: 'Order not found' });
    res.json(order);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Create order with task generation
router.post('/', auth, async (req, res) => {
  try {
    const { customerId, dateType, harvestDate, startDate, deliveryDate, deliveryOffset, 
            isRecurring, recurringFrequency, recurringEndDate, notes, items } = req.body;
    
    // Generate order number
    const count = await Order.count();
    const orderNumber = `ORD-${String(count + 1).padStart(5, '0')}`;
    
    // Calculate dates
    let finalHarvestDate = harvestDate;
    let finalDeliveryDate = deliveryDate;
    let finalStartDate = startDate;
    
    if (dateType === 'harvest' && harvestDate) {
      finalDeliveryDate = subtractDays(harvestDate, deliveryOffset || 0);
    } else if (dateType === 'start' && startDate && items?.length > 0) {
      // Calculate harvest date from start date (use longest crop cycle)
      let maxDays = 0;
      for (const item of items) {
        const product = await Product.findByPk(item.productId, { include: [Crop, MushroomSpecies] });
        if (product?.Crop) maxDays = Math.max(maxDays, product.Crop.daysToHarvest || 7);
        if (product?.MushroomSpecies) maxDays = Math.max(maxDays, product.MushroomSpecies.daysToFirstHarvest || 7);
      }
      finalHarvestDate = addDays(startDate, maxDays);
      finalDeliveryDate = subtractDays(finalHarvestDate, deliveryOffset || 0);
    }
    
    // Get customer for pricing
    const customer = await Customer.findByPk(customerId, { include: [PriceTier] });
    
    // Calculate totals
    let subtotal = 0;
    const orderItems = [];
    
    for (const item of items || []) {
      const product = await Product.findByPk(item.productId);
      if (!product) continue;
      
      // Get price for customer's tier
      let unitPrice = 0;
      if (customer?.priceTierId) {
        const priceRecord = await ProductPrice.findOne({
          where: { productId: product.id, tierId: customer.priceTierId }
        });
        unitPrice = priceRecord ? parseFloat(priceRecord.price) : 0;
      }
      
      const itemTotal = unitPrice * item.quantity;
      subtotal += itemTotal;
      
      orderItems.push({
        productId: product.id,
        quantity: item.quantity,
        unitPrice,
        total: itemTotal,
        cropId: product.cropId,
        speciesId: product.speciesId
      });
    }
    
    // Create order
    const order = await Order.create({
      farmId: req.user.farmId,
      customerId,
      orderNumber,
      dateType: dateType || 'harvest',
      harvestDate: finalHarvestDate,
      startDate: finalStartDate,
      deliveryDate: finalDeliveryDate || finalHarvestDate,
      deliveryOffset: deliveryOffset || 0,
      isRecurring: isRecurring || false,
      recurringFrequency,
      recurringEndDate,
      subtotal,
      total: subtotal,
      notes
    });
    
    // Create order items
    for (const item of orderItems) {
      await OrderItem.create({ ...item, orderId: order.id });
    }
    
    // Generate tasks
    const taskCount = await generateOrderTasks(order, req.user.farmId);
    
    res.status(201).json({ 
      order, 
      message: `Order created with ${taskCount} tasks generated` 
    });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Update order
router.put('/:id', auth, async (req, res) => {
  try {
    const order = await Order.findByPk(req.params.id);
    if (!order) return res.status(404).json({ error: 'Order not found' });
    
    const { customerId, dateType, harvestDate, startDate, deliveryDate, deliveryOffset, 
            isRecurring, recurringFrequency, recurringEndDate, notes, items } = req.body;
    
    // Update order fields
    await order.update({
      customerId,
      dateType,
      harvestDate,
      startDate,
      deliveryDate,
      deliveryOffset,
      isRecurring,
      recurringFrequency,
      recurringEndDate,
      notes
    });
    
    // Update items if provided
    if (items) {
      // Delete existing items
      await OrderItem.destroy({ where: { orderId: order.id } });
      
      // Get customer for pricing
      const customer = await Customer.findByPk(customerId, { include: [PriceTier] });
      let subtotal = 0;
      
      // Create new items
      for (const item of items) {
        const product = await Product.findByPk(item.productId);
        if (!product) continue;
        
        let unitPrice = 0;
        if (customer?.priceTierId) {
          const priceRecord = await ProductPrice.findOne({
            where: { productId: product.id, tierId: customer.priceTierId }
          });
          unitPrice = priceRecord ? parseFloat(priceRecord.price) : 0;
        }
        
        const itemTotal = unitPrice * item.quantity;
        subtotal += itemTotal;
        
        await OrderItem.create({
          orderId: order.id,
          productId: product.id,
          quantity: item.quantity,
          unitPrice,
          total: itemTotal,
          cropId: product.cropId,
          speciesId: product.speciesId
        });
      }
      
      await order.update({ subtotal, total: subtotal });
    }
    
    // Regenerate tasks
    const taskCount = await generateOrderTasks(order, req.user.farmId);
    
    res.json({ order, message: `Order updated with ${taskCount} tasks regenerated` });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Update order status
router.put('/:id/status', auth, async (req, res) => {
  try {
    const order = await Order.findByPk(req.params.id);
    if (!order) return res.status(404).json({ error: 'Order not found' });
    
    await order.update({ status: req.body.status });
    res.json(order);
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Delete single order (with task cleanup)
router.delete('/:id', auth, async (req, res) => {
  try {
    const order = await Order.findByPk(req.params.id);
    if (!order) return res.status(404).json({ error: 'Order not found' });
    
    // Delete associated tasks
    await Task.destroy({
      where: { sourceType: 'order', sourceId: order.id }
    });
    
    // Delete order (cascade deletes items)
    await order.destroy();
    
    res.json({ message: 'Order and associated tasks deleted' });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

// Bulk delete orders
router.post('/bulk-delete', auth, async (req, res) => {
  try {
    const { orderIds } = req.body;
    if (!orderIds || !Array.isArray(orderIds)) {
      return res.status(400).json({ error: 'orderIds array required' });
    }
    
    // Delete associated tasks
    await Task.destroy({
      where: { sourceType: 'order', sourceId: { [Op.in]: orderIds } }
    });
    
    // Delete orders
    const deleted = await Order.destroy({
      where: { id: { [Op.in]: orderIds } }
    });
    
    res.json({ message: `${deleted} orders and associated tasks deleted` });
  } catch (error) {
    res.status(500).json({ error: error.message });
  }
});

module.exports = router;
